version: 2
discovery:
  disable-cache: true
snapshot:
  percy-css: |
    img {
      position: absolute !important;
      clip: rect(1px, 1px, 1px, 1px);
      overflow: hidden;
      height: 1px;
      width: 1px;
      word-wrap: normal;
    }
