version: 2
discovery:
  disable-cache: true
snapshot:
  percy-css: |
    img {
      content: "";
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background: black;
      position: absolute;
    }
